-- MySQL Script generated by MySQL Workbench
-- 11/18/16 16:32:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro` DEFAULT CHARACTER SET utf8 ;
USE `cadastro` ;

-- -----------------------------------------------------
-- Table `cadastro`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`Usuario` (
  `idUsuario` INT(11) NOT NULL,
  `nome` VARCHAR(30) NULL,
  `login` VARCHAR(15) NULL,
  `senha` VARCHAR(15) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`eventos` (
  `ideventos` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `start` VARCHAR(45) NULL,
  `end` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`ideventos`, `Usuario_idUsuario`),
  INDEX `fk_eventos_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_eventos_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `cadastro`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
